package com.snapcompany.snapsafe.views.common

import androidx.compose.ui.graphics.Color

data class CustomColors(
    val firebrick: Color = Color(0xFFB22222),
    val crimson: Color = Color(0xFFFC143C),
    val coral: Color = Color(0xFFFF6060),
    val salmon: Color = Color(0xFFFA8072),
    val orange: Color = Color(0xFFFF8C00),
    val darkGoldenRod : Color = Color(0xFFB8860B),
    val gold : Color = Color(0xFFFFD700),
    val yellowBright: Color = Color(0xFFFFF162),
    val chartreuse : Color = Color(0xFF02E70B),
    val darkGreen : Color = Color(0xFF00CC63),
    val paleGreen : Color = Color(0xFF00C476),
    val mediumSpringGreen : Color = Color(0xFF00FA9A),
    val lightSeaGreen: Color = Color(0xFF20B2AA),
    val paleTurquoise: Color = Color(0xFFAFEEEE),
    val powderBlue: Color = Color(0xFFB0E0E6),
    val cadetBlue: Color = Color(0xFF5F9EA0),
    val steelBlue: Color = Color(0xFF4682B4),
    val dodgerBlue: Color = Color(0xFF1E90FF),
    val deepSkyBlue: Color = Color(0xFF00BFFF),
    val cornFlowerBlue: Color = Color(0xFF6495ED),
    val lightSkyBlue: Color = Color(0xFF87CEFA),
    val skyBlue: Color = Color(0xFF87CEEB),
    val lightBlue: Color = Color(0xFFADD8E6),
    val midnightBlue: Color = Color(0xFF0000CD),
    val navy: Color = Color(0xFF000080),
    val darkBlue: Color = Color(0xFF00008B),
    val mediumBlue: Color = Color(0xFF0000CD),
    val mediumSlateBlue: Color = Color(0xFF7B68EE),
    val mediumPurple: Color = Color(0xFF9370DB),
    val darkMagenta: Color = Color(0xFF8B008B),
    val darkViolet: Color = Color(0xFF9400D0),
    val darkOrchid: Color = Color(0xFF9932CC),
    val mediumOrchid: Color = Color(0xFFBA55D3),
    val deepPink: Color = Color(0xFFFF1493),
    val hotPink: Color = Color(0xFFFF69B4),
    val lightPink: Color = Color(0xFFFFB6C1),
    val pink: Color = Color(0xFFFFC0CB),
    val antiqueWhite: Color = Color(0xFFFAEBD7),
    val beige: Color = Color(0xFFFFF5DC),
    val saddleBrown: Color = Color(0xFF8B4513),
    val black: Color = Color(0xFF000000),
    val white: Color = Color(0xFFFFFFFF),
    val red: Color = Color(0xFFFF0000),
    val blue: Color = Color(0xFF0000FF),
    val yellow: Color = Color(0xFFFFFF00),

    )

val customColorsString: Map<String, String> = mapOf(
    "Firebrick" to "#FFB22222",
    "Crimson" to "#FFDC143C",
    "Red" to "#FFFF0000",
    "Coral" to "#FFF08080",
    "Salmon" to "#FFFA8072",
    "Orange" to "#FFFF8C00",
    "DarkGoldenRod" to "#FFB8860B",
    "Gold" to "#FFFFD700",
    "Yellow" to "#FFFFFF00",
    "Chartreuse" to "#FF7FFF00",
    "DarkGreen" to "#FF006400",
    "PaleGreen" to "#FF98FB98",
    "MediumSpringGreen" to "#FF00FA9A",
    "LightSeaGreen" to "#FF20B2AA",
    "PaleTurquoise" to "#FFAFEEEE",
    "PowderBlue" to "#FFB0E0E6",
    "CadetBlue" to "#FF5F9EA0",
    "Steel blue" to "#FF4682B4",
    "CornFlowerBlue" to "#FF6495ED",
    "DeepSkyBlue" to "#FF00BFFF",
    "DodgerBlue" to "#FF1E90FF",
    "LightBlue" to "#FFADD8E6",
    "SkyBlue" to "#FF87CEEB",
    "LightSkyBlue" to "#FF87CEFA",
    "MidnightBlue" to "#FF191970",
    "Navy" to "#FF000080",
    "DarkBlue" to "#FF00008B",
    "MediumBlue" to "#FF0000CD",
    "Blue" to "0xFF0000FF",
    "MediumSlateBlue" to "#FF7B68EE",
    "MediumPurple" to "#FF9370DB",
    "DarkMagenta" to "#FF8B008B",
    "DarkViolet" to "#FF9400D",
    "DarkOrchid" to "#FF9932CC",
    "MediumOrchid" to "#FFBA55D3",
    "DeepPink" to "#FFFF1493",
    "HotPink" to "#FFFF69B4",
    "LightPink" to "#FFFFB6C1",
    "Pink" to "#FFFFC0CB",
    "AntiqueWhite" to "#FFFAEBD7",
    "Beige" to "#FFF5F5DC",
    "SaddleBrown" to "#FF8B4513",
    "Black" to "#FF000000",
    "White" to "#FFFFFFFF"
)
